cmd /c mklink %HOMEPATH%"\.vimrc" %HOMEPATH%"\dotfiles\.vimrc"
cmd /c mklink %HOMEPATH%"\.gvimrc" %HOMEPATH%"\dotfiles\.gvimrc"
cmd /c mklink %HOMEPATH%"\.bashrc" %HOMEPATH%"\dotfiles\.bashrc"
cmd /c mklink %HOMEPATH%"\.inputrc" %HOMEPATH%"\dotfiles\.inputrc"
cmd /c mklink %HOMEPATH%"\.gitconfig" %HOMEPATH%"\dotfiles\.gitconfig"
